package org.ndexbio.enrichment.rest.services; // Note your package will be {{ groupId }}.rest

import java.net.URI;
import java.util.UUID;

import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.headers.Header;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.parameters.RequestBody;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import java.io.InputStream;
import javax.ws.rs.Consumes;
import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PathParam;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Response;
import org.ndexbio.enrichment.rest.engine.EnrichmentEngine;
import org.ndexbio.enrichment.rest.model.EnrichmentQuery;
import org.ndexbio.enrichment.rest.model.EnrichmentQueryResults;
import org.ndexbio.enrichment.rest.model.EnrichmentQueryStatus;
import org.ndexbio.enrichment.rest.model.ErrorResponse;
import org.ndexbio.enrichment.rest.model.Task;
import org.ndexbio.enrichment.rest.model.exceptions.EnrichmentException;

/**
 * Enrichment service
 * @author churas
 */
@Path(Configuration.V_ONE_PATH)
public class Enrichment {
    
    static Logger logger = LoggerFactory.getLogger(Enrichment.class);
    
    /**
     * Handles requests to do enrichment
     * @return {@link javax.ws.rs.core.Response} 
     */
    @POST 
    @Path("/")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(summary = "Submits enrichment query",
               description="Payload in JSON will have genelist which is a list of genes and databaselist which is a list of networkset names corresponding to NDEx enrichment network sets. These networks must be normalized such that “n” is gene name, “r” is gene id and “a” is alternate ids\n" +
"Initially only signor, PID, wikipathway are supported.\n" +
"\n" +
"The service should upon post return 202 and set location to resource to poll for result. Which will\n" +
"Match the URL of GET request below.",
               responses = {
                   @ApiResponse(responseCode = "202",
                           description = "The task was successfully submitted to the service. Visit the URL "
                                   + "specified in Location field in HEADERS to status and results\n",
                           headers = @Header(name = "Location", description = "URL containing resource generated by this request"),
                           content = @Content(mediaType = MediaType.APPLICATION_JSON,
                                schema = @Schema(implementation = Task.class))),
                   @ApiResponse(responseCode = "500", description = "Server Error",
                                content = @Content(mediaType = MediaType.APPLICATION_JSON,
                                schema = @Schema(implementation = ErrorResponse.class)))
               })
    public Response requestEnrichment(@RequestBody(description="Query", required = true,
                                                   content = @Content(schema = @Schema(implementation = EnrichmentQuery.class))) final String query) {
        ObjectMapper omappy = new ObjectMapper();

        try {
            // not sure why but I cannot get resteasy and jackson to worktogether to
            // automatically translate json to Query class so I'm doing it after the
            // fact
            EnrichmentEngine enricher = Configuration.getInstance().getEnrichmentEngine();
            if (enricher == null){
                throw new NullPointerException("Enrichment Engine not loaded");
            }
            EnrichmentQuery pQuery = omappy.readValue(query, EnrichmentQuery.class);
            String id = enricher.query(pQuery);
            if (id == null){
                throw new EnrichmentException("No id returned from enrichment engine");
            }
            Task t = new Task();
            t.setId(id);
            return Response.status(202).location(new URI(Configuration.getInstance().getHostURL() +
                                                         Configuration.V_ONE_PATH + "/" + id).normalize()).entity(omappy.writeValueAsString(t)).build();
        } catch(Exception ex){
            ErrorResponse er = new ErrorResponse("Error requesting enrichment", ex);
            return Response.serverError().type(MediaType.APPLICATION_JSON).entity(er.asJson()).build();
        }
    }

    @GET 
    @Path("/{id}")
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(summary = "Gets result of enrichment",
               description="NOTE: For incomplete/failed jobs only Status, message, progress, and walltime will\n" +
"be returned in JSON",
               responses = {
                   @ApiResponse(responseCode = "200",
                           description = "Success",
                           content = @Content(mediaType = MediaType.APPLICATION_JSON,
                                schema = @Schema(implementation = EnrichmentQueryResults.class))),
                   @ApiResponse(responseCode = "410",
                           description = "Task not found"),
                   @ApiResponse(responseCode = "500", description = "Server Error",
                                content = @Content(mediaType = MediaType.APPLICATION_JSON,
                                schema = @Schema(implementation = ErrorResponse.class)))
               })
    public Response getEnrichmentQueryResults(@PathParam("id") final String id,
            @Parameter(description = "Starting index of result, should be an integer 0 or larger") @QueryParam("start") int start,
            @Parameter(description = "Number of results to return, 0 for all") @QueryParam("size") int size) {
        ObjectMapper omappy = new ObjectMapper();

        try {
            EnrichmentEngine enricher = Configuration.getInstance().getEnrichmentEngine();
            if (enricher == null){
                throw new NullPointerException("Enrichment Engine not loaded");
            }
            EnrichmentQueryResults eqr = enricher.getQueryResults(id, start, size);
            if (eqr == null){
                return Response.status(410).build();
            }
            return Response.ok().type(MediaType.APPLICATION_JSON).entity(omappy.writeValueAsString(eqr)).build();
        }
        catch(Exception ex){
            ErrorResponse er = new ErrorResponse("Error getting results for id: " + id, ex);
            return Response.status(500).type(MediaType.APPLICATION_JSON).entity(er.asJson()).build();
        }
    }

    @GET 
    @Path("/{id}/status")
    @Produces(MediaType.APPLICATION_JSON)
    @Operation(summary = "Gets status of enrichment",
               description="This lets caller get status without getting the full result back",
               responses = {
                   @ApiResponse(responseCode = "200",
                           description = "Success",
                           content = @Content(mediaType = MediaType.APPLICATION_JSON,
                                schema = @Schema(implementation = EnrichmentQueryStatus.class))),
                   @ApiResponse(responseCode = "410",
                           description = "Task not found"),
                   @ApiResponse(responseCode = "500", description = "Server Error",
                                content = @Content(mediaType = MediaType.APPLICATION_JSON,
                                schema = @Schema(implementation = ErrorResponse.class)))
               })
    public Response getEnrichmentQueryStatus(@PathParam("id") final String id) {
        ObjectMapper omappy = new ObjectMapper();

        try {
            EnrichmentEngine enricher = Configuration.getInstance().getEnrichmentEngine();
            if (enricher == null){
                throw new NullPointerException("Enrichment Engine not loaded");
            }
            EnrichmentQueryStatus eqs = enricher.getQueryStatus(id);
            if (eqs ==  null){
                return Response.status(410).build();
            }
            return Response.ok().type(MediaType.APPLICATION_JSON).entity(omappy.writeValueAsString(eqs)).build();
        }
        catch(Exception ex){
            ErrorResponse er = new ErrorResponse("Error getting results for id: " + id, ex);
            return Response.serverError().type(MediaType.APPLICATION_JSON).entity(er.asJson()).build();
        }
    }

    @DELETE 
    @Path("/{id}")
    @Operation(summary = "Deletes task associated with {id} passed in",
               description="",
               responses = {
                   @ApiResponse(responseCode = "200",
                           description = "Delete request successfully received"),
                   @ApiResponse(responseCode = "400",
                           description = "Invalid delete request"),
                   @ApiResponse(responseCode = "500", description = "Server Error",
                                content = @Content(mediaType = MediaType.APPLICATION_JSON,
                                schema = @Schema(implementation = ErrorResponse.class)))
               })
    public Response deleteQueryResult(@PathParam("id") final String id) {
        ObjectMapper omappy = new ObjectMapper();

        try {
            EnrichmentEngine enricher = Configuration.getInstance().getEnrichmentEngine();
            if (enricher == null){
                throw new NullPointerException("Enrichment Engine not loaded");
            }
            enricher.delete(id);
            return Response.ok().build();
        }
        catch(Exception ex){
            ErrorResponse er = new ErrorResponse("Error deleting: " + id, ex);
            return Response.serverError().type(MediaType.APPLICATION_JSON).entity(er.asJson()).build();
        }
    }
    
    @GET 
    @Path("/{id}/overlaynetwork")
    @Operation(summary = "Gets result of enrichment from a specific database and network as CX",
               description="NOTE: For incomplete/failed 500 will be returned\n",
               responses = {
                   @ApiResponse(responseCode = "200",
                           description = "Request for overlay network successful"),
                   @ApiResponse(responseCode = "410",
                           description = "Overlay network not found"),
                   @ApiResponse(responseCode = "500", description = "Server Error",
                                content = @Content(mediaType = MediaType.APPLICATION_JSON,
                                schema = @Schema(implementation = ErrorResponse.class)))
               })
    public Response getOverlayNetwork(@PathParam("id") final String id, @Parameter(description="UUID of database") @QueryParam("databaseUUID") final String databaseUUID,
            @Parameter(description="UUID of network", required = true) @QueryParam("networkUUID") final String networkUUID) {
        ObjectMapper omappy = new ObjectMapper();
        InputStream in = null;
        try {
            EnrichmentEngine enricher = Configuration.getInstance().getEnrichmentEngine();
            if (enricher == null){
                throw new NullPointerException("Enrichment Engine not loaded");
            }
            in = enricher.getNetworkOverlayAsCX(id, databaseUUID, networkUUID);
            if (in == null){
                return Response.status(410).build();
            }
            return Response.ok().type(MediaType.APPLICATION_JSON).entity(in).build();
        }
        catch(Exception ex){
            ErrorResponse er = new ErrorResponse("Error getting overlay network for id: " + id, ex);
            return Response.serverError().type(MediaType.APPLICATION_JSON).entity(er.asJson()).build();
        }
    }
    
}